import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import AuthProvider from "@/context/Providers/AuthProvider";
import { Toaster } from "react-hot-toast";
import NavBar from "../components/NavBar/NavBar";
import SessionProviderNextAuth from "@/context/Providers/SessionProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProviderNextAuth>
          <StoreProvider>
            <AuthProvider>
              <header className="shadow-sm">
                <NavBar />
              </header>
              <main>
                {children}
              </main>
              <footer></footer>
            </AuthProvider>
          </StoreProvider>
        </SessionProviderNextAuth>
        <Toaster />
      </body>
    </html>
  );
}
